version: '3.1'
services:
  php7:
    build: ./.docker/php7
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
       XDEBUG_CONFIG: "remote_host=172.17.0.1 remote_enable=1"
